---
  - name: Install upstart conf file.
    template: src=celeryd.conf.j2 dest=/etc/init/celery_{{deployment_name}}_{{mode}}.conf mode=0600
    register: celery_install
    tags:
      - celery

  - name: restart celery
    service: name=celery_{{deployment_name}}_{{mode}} state=restarted
    sudo_user: root
    when: celery_install.changed
